### ISSUE TITLE
Add support for Mustache template for config value 

### ISSUE THREAD

**Issue by marcoslin** [fp8/simple-config#3]
Allow the value of the config to be configure as:

1. A reference to another config value using the dot notation of [ConfigStore.get](https://fp8.github.io/simple-config/classes/ConfigStore.html#get)
2. A reference to env variable using the syntax `ENV.FP8_ENV`
3. Add to `IConfigStoreOptions` setting of `customTemplateTags` for setting Mustache's [customTags](https://github.com/janl/mustache.js/#custom-delimiters)
4. Disable Mustache's HTML escape function by setting `Mustache.escape = function(text) {return text;};` ([per doc](https://github.com/janl/mustache.js/#variables))

Assuming that [loadAll](https://fp8.github.io/simple-config/interfaces/IConfigStoreOptions.html#loadAll) is set, support the following `app.yaml`:

```yaml
name: my app name

shouldBeEqualToAppName: '{{app.name}}'

array:
  - name: '{{app.name}}'
  - name: 'not app name'
  - '{{app.name}}'
  - test

# Never perform HTML escaping (ie: no need to use triple {
fp8EnvIs: '{{ENV.FP8_ENV}}'
```
